Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"

  # This box seems to have a number of problems with it.
  # My guess (or hope) is that it gets fixed soon.
  # To fix, do the following:
    # vagrant ssh
    # sudo apt-get update
    # sudo apt-get --no-install-recommends install virtualbox-guest-utils
    # exit
    # vagrant reload

  config.vm.synced_folder "../", "/richter"
  config.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 2
      v.gui = true
  end
end
